name: hub.docker.com

on:

  push:

    branches:

      - master

    paths:

      - "Dockerfile Base/Dockerfile"

    tags:

      - v*

  schedule:

    - cron: "0 */6 * * *"

    

  workflow_dispatch:    

env:

  IMAGE: amirulandalib/mltb-alpine-docker

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v2

      - name: Login to do dockerhub registry
        uses: docker/login-action@v1.14.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: startsWith(github.ref, 'refs/heads/master')

        run: echo "TAG=latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/tags')

        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: upgrade apt packages..
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build & Push

        uses: docker/build-push-action@v2.7.0

        with:

          context: ./

          file: ./Dockerfile Base/Dockerfile

          push: true

          platforms: linux/arm64/v8,linux/arm/v7,linux/amd64

          tags: amirulandalib/mltb-alpine-docker:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: amirulandalib/mltb-alpine-docker
         short-description: ${{ github.event.repository.description }}
